---
# Purge my recorder database every hour.

description: Purge Recorder Database
alias: system_recorder_purge
id: 7cce89e8-662c-4e2d-9e56-5b76cc8adb66
mode: single
trigger:
  - platform: time_pattern
    minutes: 12
action:
    - service: recorder.purge